# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageviewer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 160, 612))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_tree_band_rbg = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_tree_band_rbg.setObjectName("checkBox_tree_band_rbg")
        self.verticalLayout.addWidget(self.checkBox_tree_band_rbg)
        self.checkBox_tree_band_r = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_tree_band_r.setObjectName("checkBox_tree_band_r")
        self.verticalLayout.addWidget(self.checkBox_tree_band_r)
        self.checkBox_tree_band_b = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_tree_band_b.setObjectName("checkBox_tree_band_b")
        self.verticalLayout.addWidget(self.checkBox_tree_band_b)
        self.checkBox_tree_band_g = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_tree_band_g.setObjectName("checkBox_tree_band_g")
        self.verticalLayout.addWidget(self.checkBox_tree_band_g)
        self.checkBox_a_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_1.setObjectName("checkBox_a_1")
        self.verticalLayout.addWidget(self.checkBox_a_1)
        self.checkBox_a_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_2.setObjectName("checkBox_a_2")
        self.verticalLayout.addWidget(self.checkBox_a_2)
        self.checkBox_a_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_3.setObjectName("checkBox_a_3")
        self.verticalLayout.addWidget(self.checkBox_a_3)
        self.checkBox_a_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_4.setObjectName("checkBox_a_4")
        self.verticalLayout.addWidget(self.checkBox_a_4)
        self.checkBox_a_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_5.setObjectName("checkBox_a_5")
        self.verticalLayout.addWidget(self.checkBox_a_5)
        self.checkBox_a_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_6.setObjectName("checkBox_a_6")
        self.verticalLayout.addWidget(self.checkBox_a_6)
        self.checkBox_a_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_7.setObjectName("checkBox_a_7")
        self.verticalLayout.addWidget(self.checkBox_a_7)
        self.checkBox_a_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_a_8.setObjectName("checkBox_a_8")
        self.verticalLayout.addWidget(self.checkBox_a_8)
        self.checkBox_m_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_1.setObjectName("checkBox_m_1")
        self.verticalLayout.addWidget(self.checkBox_m_1)
        self.checkBox_m_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_2.setObjectName("checkBox_m_2")
        self.verticalLayout.addWidget(self.checkBox_m_2)
        self.checkBox_m_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_3.setObjectName("checkBox_m_3")
        self.verticalLayout.addWidget(self.checkBox_m_3)
        self.checkBox_m_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_4.setObjectName("checkBox_m_4")
        self.verticalLayout.addWidget(self.checkBox_m_4)
        self.checkBox_m_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_5.setObjectName("checkBox_m_5")
        self.verticalLayout.addWidget(self.checkBox_m_5)
        self.checkBox_m_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_6.setObjectName("checkBox_m_6")
        self.verticalLayout.addWidget(self.checkBox_m_6)
        self.checkBox_m_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_7.setObjectName("checkBox_m_7")
        self.verticalLayout.addWidget(self.checkBox_m_7)
        self.checkBox_m_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_m_8.setObjectName("checkBox_m_8")
        self.verticalLayout.addWidget(self.checkBox_m_8)
        self.checkBox_p = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_p.setObjectName("checkBox_p")
        self.verticalLayout.addWidget(self.checkBox_p)
        self.checkBox_polygon = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_polygon.setObjectName("checkBox_polygon")
        self.verticalLayout.addWidget(self.checkBox_polygon)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 131, 17))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 40, 201, 556))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_show_predictions = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_show_predictions.setObjectName("checkBox_show_predictions")
        self.verticalLayout_2.addWidget(self.checkBox_show_predictions)
        self.checkBox_show_polygons = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_show_polygons.setObjectName("checkBox_show_polygons")
        self.verticalLayout_2.addWidget(self.checkBox_show_polygons)
        self.checkBox_large_building_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_large_building_1.setObjectName("checkBox_large_building_1")
        self.verticalLayout_2.addWidget(self.checkBox_large_building_1)
        self.checkBox_res_building_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_res_building_1.setObjectName("checkBox_res_building_1")
        self.verticalLayout_2.addWidget(self.checkBox_res_building_1)
        self.checkBox_non_res_building_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_non_res_building_1.setObjectName("checkBox_non_res_building_1")
        self.verticalLayout_2.addWidget(self.checkBox_non_res_building_1)
        self.checkBox_misc_small_struct_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_misc_small_struct_2.setObjectName("checkBox_misc_small_struct_2")
        self.verticalLayout_2.addWidget(self.checkBox_misc_small_struct_2)
        self.checkBox_good_road_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_good_road_3.setObjectName("checkBox_good_road_3")
        self.verticalLayout_2.addWidget(self.checkBox_good_road_3)
        self.checkBox_poor_dirt_cart_trl_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_poor_dirt_cart_trl_4.setObjectName("checkBox_poor_dirt_cart_trl_4")
        self.verticalLayout_2.addWidget(self.checkBox_poor_dirt_cart_trl_4)
        self.checkBox_footpath_trail_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_footpath_trail_4.setObjectName("checkBox_footpath_trail_4")
        self.verticalLayout_2.addWidget(self.checkBox_footpath_trail_4)
        self.checkBox_woodlands_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_woodlands_5.setObjectName("checkBox_woodlands_5")
        self.verticalLayout_2.addWidget(self.checkBox_woodlands_5)
        self.checkBox_hedgerows_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_hedgerows_5.setObjectName("checkBox_hedgerows_5")
        self.verticalLayout_2.addWidget(self.checkBox_hedgerows_5)
        self.checkBox_group_trees_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_group_trees_5.setObjectName("checkBox_group_trees_5")
        self.verticalLayout_2.addWidget(self.checkBox_group_trees_5)
        self.checkBox_standalone_trees_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_standalone_trees_5.setObjectName("checkBox_standalone_trees_5")
        self.verticalLayout_2.addWidget(self.checkBox_standalone_trees_5)
        self.checkBox_cont_plow_crop_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_cont_plow_crop_6.setObjectName("checkBox_cont_plow_crop_6")
        self.verticalLayout_2.addWidget(self.checkBox_cont_plow_crop_6)
        self.checkBox_row_crop_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_row_crop_6.setObjectName("checkBox_row_crop_6")
        self.verticalLayout_2.addWidget(self.checkBox_row_crop_6)
        self.checkBox_waterways_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_waterways_7.setObjectName("checkBox_waterways_7")
        self.verticalLayout_2.addWidget(self.checkBox_waterways_7)
        self.checkBox_standing_water_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_standing_water_8.setObjectName("checkBox_standing_water_8")
        self.verticalLayout_2.addWidget(self.checkBox_standing_water_8)
        self.checkBox_large_vehicle_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_large_vehicle_9.setObjectName("checkBox_large_vehicle_9")
        self.verticalLayout_2.addWidget(self.checkBox_large_vehicle_9)
        self.checkBox_small_vehicle_10 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_small_vehicle_10.setObjectName("checkBox_small_vehicle_10")
        self.verticalLayout_2.addWidget(self.checkBox_small_vehicle_10)
        self.checkBox_motorbike_10 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_motorbike_10.setObjectName("checkBox_motorbike_10")
        self.verticalLayout_2.addWidget(self.checkBox_motorbike_10)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 151, 17))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(370, 40, 451, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.lineEdit_predictor_search = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_predictor_search.setObjectName("lineEdit_predictor_search")
        self.horizontalLayout.addWidget(self.lineEdit_predictor_search)
        self.comboBox_predictor_model = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_predictor_model.setMinimumSize(QtCore.QSize(225, 0))
        self.comboBox_predictor_model.setObjectName("comboBox_predictor_model")
        self.horizontalLayout.addWidget(self.comboBox_predictor_model)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(370, 80, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.lineEdit_image_search = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_image_search.setObjectName("lineEdit_image_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_image_search)
        self.comboBox_image_id = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_image_id.setMinimumSize(QtCore.QSize(225, 0))
        self.comboBox_image_id.setObjectName("comboBox_image_id")
        self.horizontalLayout_2.addWidget(self.comboBox_image_id)
        self.textEdit_statisics_output = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_statisics_output.setGeometry(QtCore.QRect(840, 40, 541, 101))
        self.textEdit_statisics_output.setObjectName("textEdit_statisics_output")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 120, 113, 39))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(820, 0, 231, 39))
        self.label_6.setObjectName("label_6")
        self.label_image_viewer = QtWidgets.QLabel(self.centralwidget)
        self.label_image_viewer.setGeometry(QtCore.QRect(400, 160, 981, 581))
        self.label_image_viewer.setText("")
        self.label_image_viewer.setObjectName("label_image_viewer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_tree_band_rbg.setText(_translate("MainWindow", "three_band RBG"))
        self.checkBox_tree_band_r.setText(_translate("MainWindow", "three_band R"))
        self.checkBox_tree_band_b.setText(_translate("MainWindow", "three_band B"))
        self.checkBox_tree_band_g.setText(_translate("MainWindow", "three_band G"))
        self.checkBox_a_1.setText(_translate("MainWindow", "A - 1"))
        self.checkBox_a_2.setText(_translate("MainWindow", "A - 2"))
        self.checkBox_a_3.setText(_translate("MainWindow", "A - 3"))
        self.checkBox_a_4.setText(_translate("MainWindow", "A - 4"))
        self.checkBox_a_5.setText(_translate("MainWindow", "A - 5"))
        self.checkBox_a_6.setText(_translate("MainWindow", "A - 6"))
        self.checkBox_a_7.setText(_translate("MainWindow", "A - 7"))
        self.checkBox_a_8.setText(_translate("MainWindow", "A - 8"))
        self.checkBox_m_1.setText(_translate("MainWindow", "M - 1"))
        self.checkBox_m_2.setText(_translate("MainWindow", "M - 2"))
        self.checkBox_m_3.setText(_translate("MainWindow", "M - 3"))
        self.checkBox_m_4.setText(_translate("MainWindow", "M - 4"))
        self.checkBox_m_5.setText(_translate("MainWindow", "M - 5"))
        self.checkBox_m_6.setText(_translate("MainWindow", "M - 6"))
        self.checkBox_m_7.setText(_translate("MainWindow", "M - 7"))
        self.checkBox_m_8.setText(_translate("MainWindow", "M - 8"))
        self.checkBox_p.setText(_translate("MainWindow", "p"))
        self.checkBox_polygon.setText(_translate("MainWindow", "polygon overlay"))
        self.label.setText(_translate("MainWindow", "Image Layers"))
        self.checkBox_show_predictions.setText(_translate("MainWindow", "Show Predictions"))
        self.checkBox_show_polygons.setText(_translate("MainWindow", "Show Polygons"))
        self.checkBox_large_building_1.setText(_translate("MainWindow", "LARGE_BUILDING:1"))
        self.checkBox_res_building_1.setText(_translate("MainWindow", "RES_BUILDING:1"))
        self.checkBox_non_res_building_1.setText(_translate("MainWindow", "NON_RES_BUILDING:1"))
        self.checkBox_misc_small_struct_2.setText(_translate("MainWindow", "MISC_SMALL_STRUCT\':2"))
        self.checkBox_good_road_3.setText(_translate("MainWindow", "GOOD_ROADS:3"))
        self.checkBox_poor_dirt_cart_trl_4.setText(_translate("MainWindow", "POOR_DIRT_CART_TR:4"))
        self.checkBox_footpath_trail_4.setText(_translate("MainWindow", "FOOTPATH_TRAIL:4"))
        self.checkBox_woodlands_5.setText(_translate("MainWindow", "WOODLAND:5"))
        self.checkBox_hedgerows_5.setText(_translate("MainWindow", "HEDGEROWS:5"))
        self.checkBox_group_trees_5.setText(_translate("MainWindow", "GROUP_TREES:5"))
        self.checkBox_standalone_trees_5.setText(_translate("MainWindow", "STANDALONE_TREES:5"))
        self.checkBox_cont_plow_crop_6.setText(_translate("MainWindow", "CONT_PLOW_CROP\':6"))
        self.checkBox_row_crop_6.setText(_translate("MainWindow", "ROW_CROP:6"))
        self.checkBox_waterways_7.setText(_translate("MainWindow", "WATERWAY:7"))
        self.checkBox_standing_water_8.setText(_translate("MainWindow", "STANDING_WATER:8"))
        self.checkBox_large_vehicle_9.setText(_translate("MainWindow", "LARGE_VEHICLE\':9"))
        self.checkBox_small_vehicle_10.setText(_translate("MainWindow", "SMALL_VEHICLE:10"))
        self.checkBox_motorbike_10.setText(_translate("MainWindow", "MOTORBIKE:10"))
        self.label_2.setText(_translate("MainWindow", "Image overlay logic"))
        self.label_3.setText(_translate("MainWindow", "Predictor model: "))
        self.label_4.setText(_translate("MainWindow", "Get Image by id: "))
        self.label_5.setText(_translate("MainWindow", "Image:"))
        self.label_6.setText(_translate("MainWindow", "Statisitc Output Log:"))

